/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicTwilioCallStatusRouteImport } from './routes/api/public/twilio/call-status'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api/public/twilio/inbound'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioCallStatusRoute =
  ApiPublicTwilioCallStatusRouteImport.update({
    id: '/api/public/twilio/call-status',
    path: '/api/public/twilio/call-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio/inbound',
  path: '/api/public/twilio/inbound',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/inbound'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicTwilioCallStatusRoute: typeof ApiPublicTwilioCallStatusRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/call-status': {
      id: '/api/public/twilio/call-status'
      path: '/api/public/twilio/call-status'
      fullPath: '/api/public/twilio/call-status'
      preLoaderRoute: typeof ApiPublicTwilioCallStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/inbound': {
      id: '/api/public/twilio/inbound'
      path: '/api/public/twilio/inbound'
      fullPath: '/api/public/twilio/inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicTwilioCallStatusRoute: ApiPublicTwilioCallStatusRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
