/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as ApiPublicTwilioCallStatusRouteImport } from './routes/api/public/twilio/call-status'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api/public/twilio/inbound'
import { Route as ApiIntegrationsGoogleOauthCallbackRouteImport } from './routes/api/integrations/google/oauth/callback'
import { Route as ApiIntegrationsGoogleOauthDiagnosticRouteImport } from './routes/api/integrations/google/oauth/diagnostic'
import { Route as ApiIntegrationsGoogleOauthUrlRouteImport } from './routes/api/integrations/google/oauth/url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiPublicTwilioCallStatusRoute =
  ApiPublicTwilioCallStatusRouteImport.update({
    id: '/api/public/twilio/call-status',
    path: '/api/public/twilio/call-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio/inbound',
  path: '/api/public/twilio/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsGoogleOauthCallbackRoute =
  ApiIntegrationsGoogleOauthCallbackRouteImport.update({
    id: '/api/integrations/google/oauth/callback',
    path: '/api/integrations/google/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleOauthDiagnosticRoute =
  ApiIntegrationsGoogleOauthDiagnosticRouteImport.update({
    id: '/api/integrations/google/oauth/diagnostic',
    path: '/api/integrations/google/oauth/diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleOauthUrlRoute =
  ApiIntegrationsGoogleOauthUrlRouteImport.update({
    id: '/api/integrations/google/oauth/url',
    path: '/api/integrations/google/oauth/url',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/api/integrations/google/oauth/callback': typeof ApiIntegrationsGoogleOauthCallbackRoute
  '/api/integrations/google/oauth/diagnostic': typeof ApiIntegrationsGoogleOauthDiagnosticRoute
  '/api/integrations/google/oauth/url': typeof ApiIntegrationsGoogleOauthUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/api/integrations/google/oauth/callback': typeof ApiIntegrationsGoogleOauthCallbackRoute
  '/api/integrations/google/oauth/diagnostic': typeof ApiIntegrationsGoogleOauthDiagnosticRoute
  '/api/integrations/google/oauth/url': typeof ApiIntegrationsGoogleOauthUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/api/public/twilio/call-status': typeof ApiPublicTwilioCallStatusRoute
  '/api/public/twilio/inbound': typeof ApiPublicTwilioInboundRoute
  '/api/integrations/google/oauth/callback': typeof ApiIntegrationsGoogleOauthCallbackRoute
  '/api/integrations/google/oauth/diagnostic': typeof ApiIntegrationsGoogleOauthDiagnosticRoute
  '/api/integrations/google/oauth/url': typeof ApiIntegrationsGoogleOauthUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/clients'
    | '/dashboard'
    | '/pipeline'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/auth/callback'
    | '/clients/$clientId'
    | '/clients/'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/inbound'
    | '/api/integrations/google/oauth/callback'
    | '/api/integrations/google/oauth/diagnostic'
    | '/api/integrations/google/oauth/url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/dashboard'
    | '/pipeline'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/auth/callback'
    | '/clients/$clientId'
    | '/clients'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/inbound'
    | '/api/integrations/google/oauth/callback'
    | '/api/integrations/google/oauth/diagnostic'
    | '/api/integrations/google/oauth/url'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campaigns'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/pipeline'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/templates'
    | '/auth/callback'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/'
    | '/api/public/twilio/call-status'
    | '/api/public/twilio/inbound'
    | '/api/integrations/google/oauth/callback'
    | '/api/integrations/google/oauth/diagnostic'
    | '/api/integrations/google/oauth/url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicTwilioCallStatusRoute: typeof ApiPublicTwilioCallStatusRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
  ApiIntegrationsGoogleOauthCallbackRoute: typeof ApiIntegrationsGoogleOauthCallbackRoute
  ApiIntegrationsGoogleOauthDiagnosticRoute: typeof ApiIntegrationsGoogleOauthDiagnosticRoute
  ApiIntegrationsGoogleOauthUrlRoute: typeof ApiIntegrationsGoogleOauthUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/twilio/call-status': {
      id: '/api/public/twilio/call-status'
      path: '/api/public/twilio/call-status'
      fullPath: '/api/public/twilio/call-status'
      preLoaderRoute: typeof ApiPublicTwilioCallStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/inbound': {
      id: '/api/public/twilio/inbound'
      path: '/api/public/twilio/inbound'
      fullPath: '/api/public/twilio/inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/oauth/callback': {
      id: '/api/integrations/google/oauth/callback'
      path: '/api/integrations/google/oauth/callback'
      fullPath: '/api/integrations/google/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/oauth/diagnostic': {
      id: '/api/integrations/google/oauth/diagnostic'
      path: '/api/integrations/google/oauth/diagnostic'
      fullPath: '/api/integrations/google/oauth/diagnostic'
      preLoaderRoute: typeof ApiIntegrationsGoogleOauthDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google/oauth/url': {
      id: '/api/integrations/google/oauth/url'
      path: '/api/integrations/google/oauth/url'
      fullPath: '/api/integrations/google/oauth/url'
      preLoaderRoute: typeof ApiIntegrationsGoogleOauthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicTwilioCallStatusRoute: ApiPublicTwilioCallStatusRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
  ApiIntegrationsGoogleOauthCallbackRoute:
    ApiIntegrationsGoogleOauthCallbackRoute,
  ApiIntegrationsGoogleOauthDiagnosticRoute:
    ApiIntegrationsGoogleOauthDiagnosticRoute,
  ApiIntegrationsGoogleOauthUrlRoute: ApiIntegrationsGoogleOauthUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
